---
- hosts: all
  become: yes
  gather_facts: yes
  serial:               #Does NOT overwrite fork config in ansible.cfg
  - 1
  - 2
  - 50%
  max_fail_percentage: 30
  tasks:
  - name:  add host entry
    lineinfile:
      path: /etc/hosts
      line: 11.22.33.44  dummy_ansible_test
